# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13deaef06693bc0b6df2f25df74193fc4cdb3e1c4f732495e887a4af50620c97b89efd81a9f2fb8f69cdc581233f1e2e2022cd001d8b06b5becd6fdc573243b4

test:
  secret_key_base: f78de4ee864b21381089b3f572f673be49cb0b71bb2fe1a85eb5ffa7f2401ebca76b8b6624240d8d7c34806878a1b09cd928d75812dced3ae4e911575b2c63b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
